server:
  port: 8082

featureflag:
  provider: unleash

spring:
  application:
    name: feature-flag-sdk


growthbook:
  server:
    url: http://localhost:3100/api
  client:
    appName: sa-exemplo-growthbook
    apiKey: 'sdk-Zo16fVKGWTpFOU1'

unleash:
  server:
    url: http://localhost:4242/api/
  client:
    appName: sa-exemplo
    instanceId: 89889
    apiKey: '*:development.fa26c4f870d57bfa54e199bf4bf9346ba142f38d66175c6b6a65fda6'
    projectName: default
    environment: development